/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaVista;

import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Color.WHITE;
import javax.swing.SwingUtilities;



/**
 *
 * @author georg
 */
public class MenuPrincipal extends javax.swing.JFrame{

    /**
     * Creates new form MenuPrincipal
     */
    
    pnlRegistrarUsuario pnlRegisUsuario = new pnlRegistrarUsuario();
    pnlActualizarUsuario pnlActuaUsuario = new pnlActualizarUsuario();
    pnlRegistrarMedidas pnlRegisMedidas = new pnlRegistrarMedidas();
    pnlActualizarMedidas pnlActuaMedidas = new pnlActualizarMedidas();
    CardLayout vista;
    public MenuPrincipal() {
        initComponents();
        vista = (CardLayout) pnlVistaPrincipal.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrarUsuario = new javax.swing.JToggleButton();
        btnActualizarMedidas = new javax.swing.JToggleButton();
        btnActualizarUsuario = new javax.swing.JToggleButton();
        btnRegistrarMedidas = new javax.swing.JToggleButton();
        pnlVistaPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUTRIHEALT");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnRegistrarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrarUsuario.setText("Registrar usuario");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarMedidas.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarMedidas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizarMedidas.setText("Actualizar medidas");
        btnActualizarMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMedidasActionPerformed(evt);
            }
        });

        btnActualizarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizarUsuario.setText("Actualizar usuario");
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });

        btnRegistrarMedidas.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarMedidas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrarMedidas.setText("Registrar medidas");
        btnRegistrarMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMedidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnRegistrarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlVistaPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pnlVistaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlVistaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1324, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnActualizarMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMedidasActionPerformed
        if(btnActualizarMedidas.isSelected()){
            pnlVistaPrincipal.add(pnlActuaMedidas,"ActualizaMedidas");
            vista.show(pnlVistaPrincipal, "ActualizaMedidas");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            
            btnRegistrarUsuario.setEnabled(false);
            btnActualizarUsuario.setEnabled(false);
            btnRegistrarMedidas.setEnabled(false);
            btnActualizarMedidas.setBackground(WHITE);
        }else{
            pnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btnRegistrarUsuario.setEnabled(true);
            btnActualizarUsuario.setEnabled(true);
            btnRegistrarMedidas.setEnabled(true);
            btnActualizarMedidas.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnActualizarMedidasActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        if(btnRegistrarUsuario.isSelected()){
            pnlVistaPrincipal.add(pnlRegisUsuario,"RegistroUsuario");
            vista.show(pnlVistaPrincipal, "RegistroUsuario");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            
            btnActualizarMedidas.setEnabled(false);
            btnActualizarUsuario.setEnabled(false);
            btnRegistrarMedidas.setEnabled(false);
            btnRegistrarUsuario.setBackground(WHITE);
        }else{
            pnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btnActualizarMedidas.setEnabled(true);
            btnActualizarUsuario.setEnabled(true);
            btnRegistrarMedidas.setEnabled(true);
            btnRegistrarUsuario.setBackground(new Color(204,204,204));
            
        }
        
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
       if(btnActualizarUsuario.isSelected()){
            pnlVistaPrincipal.add(pnlActuaUsuario,"ActualizaUsuario");
            vista.show(pnlVistaPrincipal, "ActualizaUsuario");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            
            btnRegistrarUsuario.setEnabled(false);
            btnActualizarMedidas.setEnabled(false);
            btnRegistrarMedidas.setEnabled(false);
            btnActualizarUsuario.setBackground(WHITE);
       }else{
            pnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btnRegistrarUsuario.setEnabled(true);
            btnActualizarMedidas.setEnabled(true);
            btnRegistrarMedidas.setEnabled(true);
            btnActualizarUsuario.setBackground(new Color(204,204,204));
       }
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnRegistrarMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMedidasActionPerformed
       if(btnRegistrarMedidas.isSelected()){
            pnlVistaPrincipal.add(pnlRegisMedidas,"RegistraMedidas");
            vista.show(pnlVistaPrincipal, "RegistraMedidas");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            
            btnRegistrarUsuario.setEnabled(false);
            btnActualizarUsuario.setEnabled(false);
            btnActualizarMedidas.setEnabled(false);
            btnRegistrarMedidas.setBackground(WHITE);
       }else{
            pnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btnRegistrarUsuario.setEnabled(true);
            btnActualizarUsuario.setEnabled(true);
            btnActualizarMedidas.setEnabled(true);
            btnRegistrarMedidas.setBackground(new Color(204,204,204));
       }
    }//GEN-LAST:event_btnRegistrarMedidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActualizarMedidas;
    private javax.swing.JToggleButton btnActualizarUsuario;
    private javax.swing.JToggleButton btnRegistrarMedidas;
    private javax.swing.JToggleButton btnRegistrarUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlVistaPrincipal;
    // End of variables declaration//GEN-END:variables
}
